# This is a basic workflow to help you get started with Actions

name: Unit Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt      
      - name: Run Circuit Tests
        run: |
          export PYTHONPATH=$PWD
          nose2 -s tests test_circuit
      - name: Run Controller Host Tests
        run: |
          export PYTHONPATH=$PWD
          nose2 -s tests test_controller_host
      - name: Run Layer Tests
        run: |
          export PYTHONPATH=$PWD
          nose2 -s tests test_layer
      - name: Run Layer Tests
        run: |
          export PYTHONPATH=$PWD
          nose2 -s tests test_operation
